version: "3.9"
services:
  web:
    container_name: web 
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        PHP_VERSION: '8.2.4-fpm-bullseye'
    network_mode: host
    volumes:
      - ./app:/var/www/app
    ports:
      - "3306:3306" #mysql
      - "80:80" #http
      - "443:443" #https
    extra_hosts:
      - "host.docker.internal:host-gateway"
